language: node_js
node_js: node
before_install:
  - npm install -g yarn
stages:
  - security
  - quality
  - build
cache:
  - yarn
  - directories:
      - ./dist
jobs:
  include:
    - stage: security
      script: yarn security
    - stage: quality
      name: lint
      script: yarn lint
    - stage: build
      script: yarn build
