language: node_js
node_js: node
before_install:
  - npm install -g yarn
stages:
  - security
  - quality
  # - test
  - build
  # - deploy
cache:
  - yarn
  - directories:
      - ./dist
jobs:
  include:
    - stage: security
      script: yarn security
    - stage: quality
      name: lint
      script: yarn lint
    # - stage: test
    #   name: jest
    #   script: yarn test
    - stage: build
      script: yarn build
    # - stage: deploy
    #   deploy:
    #     provider: pages
    #     skip_cleanup: true
    #     github_token: $GITHUB_TOKEN
    #     local_dir: ./build
    #     on:
    #       branch: master
